# For an explanation of the configuration and more config values,
# see https://github.com/probe-rs/cargo-embed/blob/master/src/config/default.toml
[default.probe]
protocol = "Swd"

[default.flashing]
enabled = true
restore_unwritten_bytes = false

[default.reset]
enabled = true
halt_afterwards = false

[default.general]
chip = "stm32f767zitx"
log_level = "WARN"

# Config profile that inherits from default and enables RTT (Real-Time Transfer) I/O protocol.
# Can be used with `cargo embed --config with_rtt` (does not work on Clion terminal).
[with_rtt.rtt]
enabled = true
